### PR TITLE
Web 725 anvato cleanup and security

### PR DESCRIPTION
**Pull request by WickedWolfy**
Cleanup for many Anvato Settings items to load in order, proper and not be a security issue.

Comments added, tabs proper etc.

### CODE REVIEW

**Comment by WickedWolfy** [comment]
This merge was premature... You just broke your own plugin.

**Comment by anv-devs** [comment]
What do you mean w/ premature? I did automatic merge. this version should be merged with your latest request.

**Comment by WickedWolfy** [comment]
If you would inspect the code, you would notice that not all the features were cleaned up - I have taken out the automatic setup from the 64bit key due to having a big security error: In the original code if you would provide a GET parameter, it would delete admin database values. And since the function loads for both Admin and regular user, it is a security vulnerability where a regular user can potentially delete database values.
While I have cleaned up the general functionality, the process for resetting the values, or first-set automatically, was not very well implemented. I have left it to be finished today morning.
It is my fault for creating the pull request due to my fear of losing the work, but I would have expected the code to be inspected and the missing features noticed.
All-and-all I will be working on the missing feature today in the morning, so I would guess you will need to merge another pull request in before the end of the day.

**Comment by anv-devs** [comment]
I got the security problem on automatic setup & reset settings features. You are right reset parameters can be sniffed by all users not only admins. Is there any way to do these features without using GET params? I couldn't find a way by using WP functions. These features are important for us. 

I will revert the merge, no problem.

**Comment by WickedWolfy** [comment]
Reverting now would create a conflict in the future, since the same code will be merged in later, but that is up to you. I am simply concerned that the items were merged in without an in-detail inspection, it seems, although I am honored that my changes were taken as is. =)

I am working on part 2 which is slightly more graceful way of doing the auto-setup. There are some decisions about functionality of your plugin that I can't make, since I am not part of your team, but it should give you a good handle on moving forward, if not suggest a good solution altogether.

**Comment by anv-devs** [comment]
I've reviewed your updates before merge. I did it since I was implementing missing parts of your merge. Never mind future pull requests, I will take care of it.

Please don't hesitate to share your idea about wp-plugin VIP principles. We also have the same security concerns.

Thanks!

**Comment by WickedWolfy** [comment]
I'm going to delete this branch to clean your GitHub repo.
The new pull is here: https://github.com/anv-devs/wp-anvato-plugin/pull/5

**Pull request merged**
